### ISSUE TITLE
Fond noir après CameraPreview

### ISSUE THREAD

**Issue by Zardas** [Zardas/DevMobileThalassa#5]
Après avoir arrêter la cameraPreview sur la page inventaire-comptage, toute les pages de l'appli ont un background noir.

**Comment by Zardas** [comment]
Cela a surement un rapport avec le fait de mettre le fond transparent pour que la CameraPreview puisse s'afficher en fond.

```css
html, body, ion-app, ion-content, ion-page, .nav-decor {
  background-color: transparent !important;
}
```
